name: postal_ko
description: A cross-platform Flutter package for Korean postal address search using Kakao postcode service. Supports both mobile and web platforms seamlessly.
version: 1.0.0
homepage: https://github.com/coco-de/postal_ko
repository: https://github.com/coco-de/postal_ko
issue_tracker: https://github.com/coco-de/postal_ko/issues
documentation: https://pub.dev/packages/postal_ko

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  geocoding: ^3.0.0
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/kakao_postcode_localhost.html
